---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:latest
  # build_arg_defaults:
  # EE_BASE_IMAGE: < BASE EE >

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_builder: |
    RUN pip3 install --upgrade pip setuptools
  append_final: |
    RUN cd /usr/local/bin && \
        curl -OL https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip && \
        unzip terraform_1.8.5_linux_amd64.zip && \
        rm terraform_1.8.5_linux_amd64.zip && \
        chmod +x terraform

